/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Content {
  'heroImageUrl' : string,
  'courses' : Array<Course>,
  'heroHeading' : string,
  'whyChooseUs' : Array<WhyChooseUsItem>,
  'aboutImageUrl' : string,
  'aboutText' : string,
  'heroTagline' : string,
}
export interface Course {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface Student {
  'city' : string,
  'fullName' : string,
  'email' : string,
  'courseInterest' : string,
  'phone' : string,
  'registrationDate' : string,
}
export interface WhyChooseUsItem {
  'id' : bigint,
  'title' : string,
  'description' : string,
}
export interface _SERVICE {
  'addCourse' : ActorMethod<[string, string, string], bigint>,
  'adminLogin' : ActorMethod<[string], string>,
  'adminLogout' : ActorMethod<[string], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllWhyChooseUs' : ActorMethod<[], Array<WhyChooseUsItem>>,
  'getContent' : ActorMethod<[], Content>,
  'getCoursesLength' : ActorMethod<[], bigint>,
  'getRegistrations' : ActorMethod<[string], Array<Student>>,
  'getSpecificCourse' : ActorMethod<[bigint], Course>,
  'getSpecificWhyChooseUs' : ActorMethod<[bigint], WhyChooseUsItem>,
  'getWhyChooseUsLength' : ActorMethod<[], bigint>,
  'removeCourse' : ActorMethod<[string, bigint], undefined>,
  'seedDefaults' : ActorMethod<[], undefined>,
  'submitRegistration' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'updateContent' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'updateCourse' : ActorMethod<[string, bigint, string, string], undefined>,
  'updateWhyChooseUs' : ActorMethod<
    [string, bigint, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];