/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Course = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const WhyChooseUsItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Content = IDL.Record({
  'heroImageUrl' : IDL.Text,
  'courses' : IDL.Vec(Course),
  'heroHeading' : IDL.Text,
  'whyChooseUs' : IDL.Vec(WhyChooseUsItem),
  'aboutImageUrl' : IDL.Text,
  'aboutText' : IDL.Text,
  'heroTagline' : IDL.Text,
});
export const Student = IDL.Record({
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'courseInterest' : IDL.Text,
  'phone' : IDL.Text,
  'registrationDate' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Text], []),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllWhyChooseUs' : IDL.Func([], [IDL.Vec(WhyChooseUsItem)], ['query']),
  'getContent' : IDL.Func([], [Content], ['query']),
  'getCoursesLength' : IDL.Func([], [IDL.Nat], ['query']),
  'getRegistrations' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getSpecificCourse' : IDL.Func([IDL.Nat], [Course], ['query']),
  'getSpecificWhyChooseUs' : IDL.Func([IDL.Nat], [WhyChooseUsItem], ['query']),
  'getWhyChooseUsLength' : IDL.Func([], [IDL.Nat], ['query']),
  'removeCourse' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'seedDefaults' : IDL.Func([], [], []),
  'submitRegistration' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateContent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateCourse' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateWhyChooseUs' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const WhyChooseUsItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Content = IDL.Record({
    'heroImageUrl' : IDL.Text,
    'courses' : IDL.Vec(Course),
    'heroHeading' : IDL.Text,
    'whyChooseUs' : IDL.Vec(WhyChooseUsItem),
    'aboutImageUrl' : IDL.Text,
    'aboutText' : IDL.Text,
    'heroTagline' : IDL.Text,
  });
  const Student = IDL.Record({
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'courseInterest' : IDL.Text,
    'phone' : IDL.Text,
    'registrationDate' : IDL.Text,
  });
  
  return IDL.Service({
    'addCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Text], []),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllWhyChooseUs' : IDL.Func([], [IDL.Vec(WhyChooseUsItem)], ['query']),
    'getContent' : IDL.Func([], [Content], ['query']),
    'getCoursesLength' : IDL.Func([], [IDL.Nat], ['query']),
    'getRegistrations' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getSpecificCourse' : IDL.Func([IDL.Nat], [Course], ['query']),
    'getSpecificWhyChooseUs' : IDL.Func(
        [IDL.Nat],
        [WhyChooseUsItem],
        ['query'],
      ),
    'getWhyChooseUsLength' : IDL.Func([], [IDL.Nat], ['query']),
    'removeCourse' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'seedDefaults' : IDL.Func([], [], []),
    'submitRegistration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateCourse' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateWhyChooseUs' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };