/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Student {
    city: string;
    fullName: string;
    email: string;
    courseInterest: string;
    phone: string;
    registrationDate: string;
}
export interface WhyChooseUsItem {
    id: bigint;
    title: string;
    description: string;
}
export interface Content {
    heroImageUrl: string;
    courses: Array<Course>;
    heroHeading: string;
    whyChooseUs: Array<WhyChooseUsItem>;
    aboutImageUrl: string;
    aboutText: string;
    heroTagline: string;
}
export interface Course {
    id: bigint;
    name: string;
    description: string;
}
export interface backendInterface {
    addCourse(sessionToken: string, name: string, description: string): Promise<bigint>;
    adminLogin(password: string): Promise<string>;
    adminLogout(token: string): Promise<void>;
    getAllCourses(): Promise<Array<Course>>;
    getAllWhyChooseUs(): Promise<Array<WhyChooseUsItem>>;
    getContent(): Promise<Content>;
    getCoursesLength(): Promise<bigint>;
    getRegistrations(sessionToken: string): Promise<Array<Student>>;
    getSpecificCourse(courseId: bigint): Promise<Course>;
    getSpecificWhyChooseUs(whyChooseUsId: bigint): Promise<WhyChooseUsItem>;
    getWhyChooseUsLength(): Promise<bigint>;
    removeCourse(sessionToken: string, id: bigint): Promise<void>;
    seedDefaults(): Promise<void>;
    submitRegistration(fullName: string, email: string, phone: string, courseInterest: string, city: string, registrationDate: string): Promise<void>;
    updateContent(sessionToken: string, heroHeading: string, heroTagline: string, aboutText: string, heroImageUrl: string, aboutImageUrl: string): Promise<void>;
    updateCourse(sessionToken: string, id: bigint, name: string, description: string): Promise<void>;
    updateWhyChooseUs(sessionToken: string, id: bigint, title: string, description: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCourse(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCourse(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCourse(arg0, arg1, arg2);
            return result;
        }
    }
    async adminLogin(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0);
            return result;
        }
    }
    async adminLogout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout(arg0);
            return result;
        }
    }
    async getAllCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourses();
            return result;
        }
    }
    async getAllWhyChooseUs(): Promise<Array<WhyChooseUsItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWhyChooseUs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWhyChooseUs();
            return result;
        }
    }
    async getContent(): Promise<Content> {
        if (this.processError) {
            try {
                const result = await this.actor.getContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContent();
            return result;
        }
    }
    async getCoursesLength(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesLength();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesLength();
            return result;
        }
    }
    async getRegistrations(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistrations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistrations(arg0);
            return result;
        }
    }
    async getSpecificCourse(arg0: bigint): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpecificCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpecificCourse(arg0);
            return result;
        }
    }
    async getSpecificWhyChooseUs(arg0: bigint): Promise<WhyChooseUsItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpecificWhyChooseUs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpecificWhyChooseUs(arg0);
            return result;
        }
    }
    async getWhyChooseUsLength(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWhyChooseUsLength();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWhyChooseUsLength();
            return result;
        }
    }
    async removeCourse(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCourse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCourse(arg0, arg1);
            return result;
        }
    }
    async seedDefaults(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDefaults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDefaults();
            return result;
        }
    }
    async submitRegistration(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRegistration(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRegistration(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateContent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContent(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContent(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateCourse(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateWhyChooseUs(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWhyChooseUs(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWhyChooseUs(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
